openapi: 3.0.3
info:
  title: Applikuj API
  version: 1.0.0
  description: Applikuj REST API

servers:
  - url: /api

components:
  securitySchemes:
    sanctum:
      type: http
      scheme: bearer

  schemas:
    User:
      $ref: "./components/schemas/User.yml"
    ValidationError:
      $ref: "./components/schemas/ValidationError.yml"

paths:
  /user:
    $ref: "./paths/user.yml"
  /email/verify/{id}/{token}:
    $ref: "./paths/email_verify.yml"
  /email/resend:
    $ref: "./paths/email_resend.yml"
